- .github/workflows/actions/release-packages/action.yml
- .github/workflows/build.yml
<details>
<summary>📦 Published PR as canary version: <code>0.0.1--canary.2.a3deb21.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.0.1--canary.2.a3deb21.0
npm install @ukho/admiralty-core@0.0.1--canary.2.a3deb21.0
yarn add @ukho/admiralty-angular@0.0.1--canary.2.a3deb21.0
yarn add @ukho/admiralty-core@0.0.1--canary.2.a3deb21.0
```
</details>
> Fixing Auto admin access to the repo

- .github/workflows/actions/build-core/action.yml
- yarn.lock
Fixes #4 
<details>
<summary>📦 Published PR as canary version: <code>0.0.6--canary.5.7d9a081.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.0.6--canary.5.7d9a081.0
npm install @ukho/admiralty-core@0.0.6--canary.5.7d9a081.0
yarn add @ukho/admiralty-angular@0.0.6--canary.5.7d9a081.0
yarn add @ukho/admiralty-core@0.0.6--canary.5.7d9a081.0
```
</details>
> Fixing the stylesheets and webfonts missing from the NPM package

- .github/workflows/actions/release-packages/action.yml
- packages/angular/.scripts/copyPackageVersion.js
- packages/angular/package.json
Fixes: #57 
<details>
<summary>📦 Published PR as canary version: <code>0.1.1--canary.60.d408a38.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.1.1--canary.60.d408a38.0
npm install @ukho/admiralty-core@0.1.1--canary.60.d408a38.0
yarn add @ukho/admiralty-angular@0.1.1--canary.60.d408a38.0
yarn add @ukho/admiralty-core@0.1.1--canary.60.d408a38.0
```
</details>
> Fixing the package version desync

- package.json
- packages/angular/src/lib/stencil-generated/components.ts
- packages/core/src/components.d.ts
- packages/core/src/components/textarea/readme.md
- packages/core/src/components/textarea/textarea.stories.ts
- packages/core/src/components/textarea/textarea.tsx
<details>
<summary>📦 Published PR as canary version: <code>0.1.2--canary.65.baab903.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.1.2--canary.65.baab903.0
npm install @ukho/admiralty-core@0.1.2--canary.65.baab903.0
yarn add @ukho/admiralty-angular@0.1.2--canary.65.baab903.0
yarn add @ukho/admiralty-core@0.1.2--canary.65.baab903.0
```
</details>
> fix: admiralty textarea does not support maxlength

- packages/angular/src/index.ts
- packages/angular/src/lib/stencil-generated/components.ts
- packages/core/src/components.d.ts
- packages/core/src/components/file-input/file-input.interface.ts
- packages/core/src/components/file-input/file-input.spec.ts
- packages/core/src/components/file-input/file-input.tsx
- packages/core/src/components/file-input/readme.md
Fixes #77 
<details>
<summary>📦 Published PR as canary version: <code>0.3.2--canary.75.9ff44a4.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.3.2--canary.75.9ff44a4.0
npm install @ukho/admiralty-core@0.3.2--canary.75.9ff44a4.0
yarn add @ukho/admiralty-angular@0.3.2--canary.75.9ff44a4.0
yarn add @ukho/admiralty-core@0.3.2--canary.75.9ff44a4.0
```
</details>
> Adding a custom file input event

- packages/angular/src/index.ts
- packages/angular/src/lib/stencil-generated/components.ts
- packages/core/src/components.d.ts
- packages/core/src/components/textarea/readme.md
- packages/core/src/components/textarea/textarea.interface.ts
- packages/core/src/components/textarea/textarea.spec.ts
- packages/core/src/components/textarea/textarea.stories.ts
- packages/core/src/components/textarea/textarea.tsx
- packages/test-app/src/app/app.component.html
- packages/test-app/src/app/app.component.ts
Fixes: #78 
<details>
<summary>📦 Published PR as canary version: <code>0.3.3--canary.79.047a94a.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.3.3--canary.79.047a94a.0
npm install @ukho/admiralty-core@0.3.3--canary.79.047a94a.0
yarn add @ukho/admiralty-angular@0.3.3--canary.79.047a94a.0
yarn add @ukho/admiralty-core@0.3.3--canary.79.047a94a.0
```
</details>
> Fix textarea so that it works with the Angular form controls

- packages/core/src/components.d.ts
- packages/core/src/components/type-ahead-item/readme.md
- packages/core/src/components/type-ahead-item/type-ahead-item.tsx
- packages/core/src/components/type-ahead/test/type-ahead.spec.ts
- packages/core/src/components/type-ahead/type-ahead.tsx
- packages/test-app/src/app/app.component.html
- packages/test-app/src/app/app.component.ts
<details>
<summary>📦 Published PR as canary version: <code>0.3.4--canary.80.acfa172.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.3.4--canary.80.acfa172.0
npm install @ukho/admiralty-core@0.3.4--canary.80.acfa172.0
yarn add @ukho/admiralty-angular@0.3.4--canary.80.acfa172.0
yarn add @ukho/admiralty-core@0.3.4--canary.80.acfa172.0
```
</details>
> fix: admiralty type ahead item fails to append value on dynamic data

- .devcontainer/devcontainer.json
- packages/core/src/components/input/input.spec.ts
- packages/core/src/components/input/input.tsx
<details>
<summary>📦 Published PR as canary version: <code>0.3.5--canary.82.b10cedb.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.3.5--canary.82.b10cedb.0
npm install @ukho/admiralty-core@0.3.5--canary.82.b10cedb.0
yarn add @ukho/admiralty-angular@0.3.5--canary.82.b10cedb.0
yarn add @ukho/admiralty-core@0.3.5--canary.82.b10cedb.0
```
</details>
> fix: input component invalid error message layout space not reserved when not displayed

- packages/core/src/components/type-ahead/type-ahead.scss
Fixes #84 
Fixes #81 
<details>
<summary>📦 Published PR as canary version: <code>0.3.6--canary.85.53b5461.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.3.6--canary.85.53b5461.0
npm install @ukho/admiralty-core@0.3.6--canary.85.53b5461.0
yarn add @ukho/admiralty-angular@0.3.6--canary.85.53b5461.0
yarn add @ukho/admiralty-core@0.3.6--canary.85.53b5461.0
```
</details>
> fix: Typeahead drawer positioning

- packages/core/src/components/progress-bar/progress-bar.scss
<details>
<summary>📦 Published PR as canary version: <code>0.3.7--canary.83.50cb2cc.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.3.7--canary.83.50cb2cc.0
npm install @ukho/admiralty-core@0.3.7--canary.83.50cb2cc.0
yarn add @ukho/admiralty-angular@0.3.7--canary.83.50cb2cc.0
yarn add @ukho/admiralty-core@0.3.7--canary.83.50cb2cc.0
```
</details>
> fix: progress bar colours in Firefox

- packages/core/src/components/input/input.spec.ts
- packages/core/src/components/input/input.tsx
- packages/core/src/components/textarea/textarea.spec.ts
- packages/core/src/components/textarea/textarea.tsx
<details>
<summary>📦 Published PR as canary version: <code>0.4.2--canary.101.582f0bd.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.4.2--canary.101.582f0bd.0
npm install @ukho/admiralty-core@0.4.2--canary.101.582f0bd.0
yarn add @ukho/admiralty-angular@0.4.2--canary.101.582f0bd.0
yarn add @ukho/admiralty-core@0.4.2--canary.101.582f0bd.0
```
</details>
> fix: admiralty input validation displays exclamation mark when invalid message is not provided

- packages/angular/src/lib/stencil-generated/components.ts
- packages/angular/src/lib/stencil-generated/number-value-accessor.ts
- packages/angular/src/lib/stencil-generated/text-value-accessor.ts
- packages/core/src/components.d.ts
- packages/core/src/components/input/input.tsx
- packages/core/src/components/input/readme.md
- packages/core/stencil.config.ts
switching admiralty-input to emit 'admiraltyInput' rather than 'admiraltyChange'
Fixes: #95 
<details>
<summary>📦 Published PR as canary version: <code>0.4.3--canary.103.091eddf.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.4.3--canary.103.091eddf.0
npm install @ukho/admiralty-core@0.4.3--canary.103.091eddf.0
yarn add @ukho/admiralty-angular@0.4.3--canary.103.091eddf.0
yarn add @ukho/admiralty-core@0.4.3--canary.103.091eddf.0
```
</details>
> Fix: Input and Radio Group event names clashing

- packages/angular/src/lib/stencil-generated/components.ts
- packages/core/src/components.d.ts
- packages/core/src/components/textarea/readme.md
- packages/core/src/components/textarea/textarea.tsx
<details>
<summary>📦 Published PR as canary version: <code>0.4.4--canary.104.a73ac95.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.4.4--canary.104.a73ac95.0
npm install @ukho/admiralty-core@0.4.4--canary.104.a73ac95.0
yarn add @ukho/admiralty-angular@0.4.4--canary.104.a73ac95.0
yarn add @ukho/admiralty-core@0.4.4--canary.104.a73ac95.0
```
</details>
> Fixing the text area event name change that was forgotten

- packages/core/src/components/radio-group/radio-group.tsx
- packages/core/src/components/radio/radio.tsx
The radio buttons will now correctly show when you click between the label and the dot
Fixes: #61 
<details>
<summary>📦 Published PR as canary version: <code>0.4.5--canary.105.a14b51d.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.4.5--canary.105.a14b51d.0
npm install @ukho/admiralty-core@0.4.5--canary.105.a14b51d.0
yarn add @ukho/admiralty-angular@0.4.5--canary.105.a14b51d.0
yarn add @ukho/admiralty-core@0.4.5--canary.105.a14b51d.0
```
</details>
> Fixing the radio component hit detection

- packages/core/src/components/file-input/file-input.scss
- packages/core/src/components/file-input/file-input.spec.ts
- packages/core/src/components/file-input/file-input.tsx
<details>
<summary>📦 Published PR as canary version: <code>0.6.0--canary.120.fd724b8.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.6.0--canary.120.fd724b8.0
npm install @ukho/admiralty-core@0.6.0--canary.120.fd724b8.0
yarn add @ukho/admiralty-angular@0.6.0--canary.120.fd724b8.0
yarn add @ukho/admiralty-core@0.6.0--canary.120.fd724b8.0
```
</details>
> feat: Remove admiralty-file-input label update behaviour when files are selected

- packages/angular/src/lib/stencil-generated/components.ts
- packages/core/src/components.d.ts
- packages/core/src/components/file-input/file-input.scss
- packages/core/src/components/file-input/file-input.spec.ts
- packages/core/src/components/file-input/file-input.stories.ts
- packages/core/src/components/file-input/file-input.tsx
- packages/core/src/components/file-input/readme.md
- packages/core/src/components/input-invalid/readme.md
<details>
<summary>📦 Published PR as canary version: <code>0.6.0--canary.121.9ba070a.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.6.0--canary.121.9ba070a.0
npm install @ukho/admiralty-core@0.6.0--canary.121.9ba070a.0
yarn add @ukho/admiralty-angular@0.6.0--canary.121.9ba070a.0
yarn add @ukho/admiralty-core@0.6.0--canary.121.9ba070a.0
```
</details>
> feat: Add invalid and invalidMessage to File Input and remove layout bottom margin

- packages/core/src/components/file-input/file-input.scss
- packages/core/src/components/file-input/file-input.spec.ts
- packages/core/src/components/file-input/file-input.tsx
<details>
<summary>📦 Published PR as canary version: <code>0.7.1--canary.123.1355e01.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.7.1--canary.123.1355e01.0
npm install @ukho/admiralty-core@0.7.1--canary.123.1355e01.0
yarn add @ukho/admiralty-angular@0.7.1--canary.123.1355e01.0
yarn add @ukho/admiralty-core@0.7.1--canary.123.1355e01.0
```
</details>
> fix: Add missing border style for invalid file input

- packages/angular/src/lib/stencil-generated/components.ts
- packages/core/src/components.d.ts
- packages/core/src/components/colour-block/colour-block.spec.ts
- packages/core/src/components/colour-block/colour-block.stories.ts
- packages/core/src/components/colour-block/colour-block.tsx
- packages/core/src/components/colour-block/readme.md
- packages/docs/components/colour-block/events.mdx
- packages/docs/components/colour-block/props.mdx
- packages/docs/plugins/websiteDocsGenerator.ts
- packages/test-app/src/app/app.component.html
- packages/website/src/components/colour-blocks/colour-blocks.tsx
<details>
<summary>📦 Published PR as canary version: <code>0.8.0--canary.139.1ac840a.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.8.0--canary.139.1ac840a.0
npm install @ukho/admiralty-core@0.8.0--canary.139.1ac840a.0
yarn add @ukho/admiralty-angular@0.8.0--canary.139.1ac840a.0
yarn add @ukho/admiralty-core@0.8.0--canary.139.1ac840a.0
```
</details>
> fix: Replace colour block click action with colourBlockLinkClicked event

- packages/angular/src/lib/stencil-generated/components.ts
- packages/core/src/components.d.ts
- packages/core/src/components/header-profile/header-profile.tsx
- packages/core/src/components/header-profile/readme.md
- packages/core/src/components/header/header.stories.ts
- packages/docs/components/header-profile/events.mdx
- packages/docs/components/header-profile/props.mdx
<details>
<summary>📦 Published PR as canary version: <code>0.10.0--canary.150.0fef015.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.10.0--canary.150.0fef015.0
npm install @ukho/admiralty-core@0.10.0--canary.150.0fef015.0
yarn add @ukho/admiralty-angular@0.10.0--canary.150.0fef015.0
yarn add @ukho/admiralty-core@0.10.0--canary.150.0fef015.0
```
</details>
> Adding the ability to turn off the signout and account button on the header profile

- packages/core/src/components/modal-dialog/modal-dialog.stories.ts
- packages/core/src/components/tab-group/tab-group.tsx
- packages/website/src/app/components/layout.tsx
- packages/website/src/app/components/styles.module.css
- packages/website/src/components/copy-code-snippet/copy-code-snippet.tsx
- packages/website/src/usage/modal-dialog/basic/angular.mdx
- packages/website/src/usage/modal-dialog/basic/javascript.mdx
- packages/website/src/usage/modal-dialog/basic/react.mdx
Prevent the code examples on the component page from increasing the parent width beyond the visible width.
The code example will now scroll if the width exceeds the parent.
Before:
After:
Also fixed in this update is an issue where the default tab would not be selected when navigating between component pages.
Before:
After:
<details>
<summary>📦 Published PR as canary version: <code>0.14.2--canary.228.7b3918b.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.14.2--canary.228.7b3918b.0
npm install @ukho/admiralty-core@0.14.2--canary.228.7b3918b.0
yarn add @ukho/admiralty-angular@0.14.2--canary.228.7b3918b.0
yarn add @ukho/admiralty-core@0.14.2--canary.228.7b3918b.0
```
</details>
> fix: page width on design system website

- packages/core/src/components/autocomplete/autocomplete.tsx
When the autocomplete and autocomplete options are rendered asynchronously, e.g. via an API, the initial value for the autocomplete was being cleared internally.
Add a check to only update the internal state if the options have rendered.
<details>
<summary>📦 Published PR as canary version: <code>0.18.1--canary.239.55e7b19.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@0.18.1--canary.239.55e7b19.0
npm install @ukho/admiralty-core@0.18.1--canary.239.55e7b19.0
yarn add @ukho/admiralty-angular@0.18.1--canary.239.55e7b19.0
yarn add @ukho/admiralty-core@0.18.1--canary.239.55e7b19.0
```
</details>
> Do not clear autocomplete default value before options have been rendered

- packages/core/src/components/header-menu-item/header-menu-item.scss
- packages/core/src/components/header-menu-link/header-menu-link.scss
- packages/core/src/components/header-profile/header-profile.scss
- packages/core/src/components/header-profile/header-profile.spec.ts
- packages/core/src/components/header-profile/header-profile.tsx
- packages/core/src/components/header-sub-menu-item/header-sub-menu-item.scss
- packages/core/src/components/header/header.scss
- packages/core/src/components/header/header.spec.ts
- packages/core/src/components/header/header.tsx
- packages/core/src/components/skip-link/skip-link.scss
- packages/core/src/components/skip-link/skip-link.spec.ts
- packages/core/src/components/skip-link/skip-link.tsx
Update focus states that were missed in [PR 248](https://github.com/UKHO/admiralty-design-system/pull/248)
Also updated all header text colours to match the Figma design.
<details>
<summary>📦 Published PR as canary version: <code>1.0.1--canary.254.8b34623.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@1.0.1--canary.254.8b34623.0
npm install @ukho/admiralty-core@1.0.1--canary.254.8b34623.0
yarn add @ukho/admiralty-angular@1.0.1--canary.254.8b34623.0
yarn add @ukho/admiralty-core@1.0.1--canary.254.8b34623.0
```
</details>
> Update focus highlights for header mobile menus 

- packages/core/src/themes/default.css
<details>
<summary>📦 Published PR as canary version: <code>2.0.0--canary.265.91e8ce6.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@2.0.0--canary.265.91e8ce6.0
npm install @ukho/admiralty-core@2.0.0--canary.265.91e8ce6.0
yarn add @ukho/admiralty-angular@2.0.0--canary.265.91e8ce6.0
yarn add @ukho/admiralty-core@2.0.0--canary.265.91e8ce6.0
```
</details>
> Replace incorrect colour definition for info dialogue

- packages/angular/src/lib/stencil-generated/components.ts
- packages/core/src/components.d.ts
- packages/core/src/components/header-profile/header-profile.spec.ts
- packages/core/src/components/header-profile/header-profile.tsx
- packages/core/src/components/header-sub-menu-item/header-sub-menu-item.e2e.ts
- packages/core/src/components/header-sub-menu-item/header-sub-menu-item.scss
- packages/core/src/components/header-sub-menu-item/header-sub-menu-item.spec.ts
- packages/core/src/components/header-sub-menu-item/header-sub-menu-item.tsx
- packages/core/src/components/header-sub-menu-item/readme.md
- packages/core/src/components/header/header.stories.data.ts
- packages/core/src/components/header/header.stories.ts
- packages/core/src/components/header/header.types.ts
- packages/core/src/components/side-nav-item/side-nav-item.spec.ts
- packages/core/src/components/side-nav-item/side-nav-item.tsx
- packages/core/src/components/side-nav/side-nav.spec.ts
- packages/website/src/app/components/header/header.mdx
- packages/website/src/usage/header/menu-item/angular.mdx
- packages/website/src/usage/header/menu-item/javascript.mdx
- packages/website/src/usage/header/menu-item/react.mdx
Sub menu items were being rendered as `<div>` tags with event listeners. This goes against best practice.
Menu items in the Header component should be rendered as buttons or links. If the menu opens another menu the item should be a button. If the item redirect the user to another page then it should be a link.
When the `href` property is supplied to the `HeaderSubMenuItemComponent` it will now render an `<a>` tag.
The correct structure for a menu is:
```html
<admiralty-header>
<admiralty-header-menu-item menu-title="Item 1" slot="items">
<admiralty-header-sub-menu-item menu-title="Sub menu item 1" href="/item-1-1" />
<admiralty-header-sub-menu-item menu-title="Sub menu item 2" href="/item-1-2" />
</admiralty-header-menu-item>
<admiralty-header-menu-link menu-title="Item 2" href="/item-2" …
```
> fix: Header sub menu items should be links

- MIGRATION_GUIDE.md
- packages/website/src/app/getting-started/layout.tsx
- packages/website/src/app/getting-started/migrating/migrating.mdx
- packages/website/src/app/getting-started/migrating/page.tsx
Document the changes needed to use version 2.0 of the design system.
Will be available at `/getting-started/migrating` on the website.
<details>
<summary>📦 Published PR as canary version: <code>2.0.0--canary.275.9a50db5.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@2.0.0--canary.275.9a50db5.0
npm install @ukho/admiralty-core@2.0.0--canary.275.9a50db5.0
npm install @ukho/admiralty-react@2.0.0--canary.275.9a50db5.0
yarn add @ukho/admiralty-angular@2.0.0--canary.275.9a50db5.0
yarn add @ukho/admiralty-core@2.0.0--canary.275.9a50db5.0
yarn add @ukho/admiralty-react@2.0.0--canary.275.9a50db5.0
```
</details>
> Create migration guide for v2.0

- packages/core/src/components/expansion/expansion.tsx
- packages/core/src/components/radio-group/radio-group.tsx
- packages/core/src/components/read-more/read-more.tsx
`id` was conflicting with the native HTML `id` attribute.
<details>
<summary>📦 Published PR as canary version: <code>2.0.0--canary.276.d611002.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@2.0.0--canary.276.d611002.0
npm install @ukho/admiralty-core@2.0.0--canary.276.d611002.0
npm install @ukho/admiralty-react@2.0.0--canary.276.d611002.0
yarn add @ukho/admiralty-angular@2.0.0--canary.276.d611002.0
yarn add @ukho/admiralty-core@2.0.0--canary.276.d611002.0
yarn add @ukho/admiralty-react@2.0.0--canary.276.d611002.0
```
</details>
> fix: rename id to be internalId

- packages/website/src/app/accessbility/accessibility.mdx
- packages/website/src/app/accessbility/layout.tsx
- packages/website/src/app/accessbility/page.tsx
- packages/website/src/app/accessbility/styles.module.css
- packages/website/src/app/layout.tsx
Implemented a accessibility page for the design system website. (Replica of Kai's accessibility page)
[[Feature] Add accessibility statement to the DS website](#186)
<details>
<summary>📦 Published PR as canary version: <code>3.1.0--canary.283.f72feac.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@3.1.0--canary.283.f72feac.0
npm install @ukho/admiralty-core@3.1.0--canary.283.f72feac.0
npm install @ukho/admiralty-react@3.1.0--canary.283.f72feac.0
yarn add @ukho/admiralty-angular@3.1.0--canary.283.f72feac.0
yarn add @ukho/admiralty-core@3.1.0--canary.283.f72feac.0
yarn add @ukho/admiralty-react@3.1.0--canary.283.f72feac.0
```
</details>
> Feat: Add accessibility statement to the DS website

- packages/core/src/components/select/select.spec.ts
- packages/core/src/components/select/select.stories.ts
Introduced documentation on how to implement a placeholder option, with the current state.
[Select - add instruction text in input [Feature]](#145)
Here you can see the placeholder option informing the user to "select an option"
<details>
<summary>📦 Published PR as canary version: <code>4.0.0--canary.271.95bebc9.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@4.0.0--canary.271.95bebc9.0
npm install @ukho/admiralty-core@4.0.0--canary.271.95bebc9.0
npm install @ukho/admiralty-react@4.0.0--canary.271.95bebc9.0
yarn add @ukho/admiralty-angular@4.0.0--canary.271.95bebc9.0
yarn add @ukho/admiralty-core@4.0.0--canary.271.95bebc9.0
yarn add @ukho/admiralty-react@4.0.0--canary.271.95bebc9.0
```
</details>
> Feat: Include documentation to demonstrate a placeholder option

- packages/website/src/app/components/dialogue/dialogue.mdx
- packages/website/src/app/components/modal-dialog/modal-dialog.mdx
- packages/website/src/app/components/read-more/read-more.mdx
Updated the documentation to include a "Content Design" section for the 'Modal dialogue', 'Dialogue' and 'Read more' components
[[Feature] Content update](#220)
Modal dialogue
Dialogue
Read More
<details>
<summary>📦 Published PR as canary version: <code>4.0.0--canary.272.0aa408a.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@4.0.0--canary.272.0aa408a.0
npm install @ukho/admiralty-core@4.0.0--canary.272.0aa408a.0
npm install @ukho/admiralty-react@4.0.0--canary.272.0aa408a.0
yarn add @ukho/admiralty-angular@4.0.0--canary.272.0aa408a.0
yarn add @ukho/admiralty-core@4.0.0--canary.272.0aa408a.0
yarn add @ukho/admiralty-react@4.0.0--canary.272.0aa408a.0
```
</details>
> Feat: updated documentation for content design

- packages/core/src/components/hint/hint.vars.scss
- packages/core/src/components/label/label.vars.scss
- packages/core/src/themes/default.css
[[BUG] Accessibility: Disable Input labels and hint text fail WCAG 1.4.3](#160)
Applied colour hex #757575 to the hint and label disabled styles, to meeting accessibility requirements.
Closed [fix: Make disabled colours pass AA colour contrast](#205) due to merge conflicts. 
<details>
<summary>📦 Published PR as canary version: <code>3.0.2--canary.288.f5b6f00.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@3.0.2--canary.288.f5b6f00.0
npm install @ukho/admiralty-core@3.0.2--canary.288.f5b6f00.0
npm install @ukho/admiralty-react@3.0.2--canary.288.f5b6f00.0
yarn add @ukho/admiralty-angular@3.0.2--canary.288.f5b6f00.0
yarn add @ukho/admiralty-core@3.0.2--canary.288.f5b6f00.0
yarn add …
```
> Fix: Accessibility Disable Input labels and hint text fail WCAG 1.4.3 

- .github/workflows/actions/build-all/action.yml
Fixes the build pipeline to include the theme file.
Fixes #306 
[Missing theme file](https://github.com/UKHO/admiralty-design-system/issues/306)
<details>
<summary>📦 Published PR as canary version: <code>3.1.1--canary.308.1f65212.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@3.1.1--canary.308.1f65212.0
npm install @ukho/admiralty-core@3.1.1--canary.308.1f65212.0
npm install @ukho/admiralty-react@3.1.1--canary.308.1f65212.0
yarn add @ukho/admiralty-angular@3.1.1--canary.308.1f65212.0
yarn add @ukho/admiralty-core@3.1.1--canary.308.1f65212.0
yarn add @ukho/admiralty-react@3.1.1--canary.308.1f65212.0
```
</details>
> Fix: theme file missing when packaged

- packages/core/src/themes/default.css
<details>
<summary>📦 Published PR as canary version: <code>4.0.0--canary.313.f7733aa.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@4.0.0--canary.313.f7733aa.0
npm install @ukho/admiralty-core@4.0.0--canary.313.f7733aa.0
npm install @ukho/admiralty-react@4.0.0--canary.313.f7733aa.0
yarn add @ukho/admiralty-angular@4.0.0--canary.313.f7733aa.0
yarn add @ukho/admiralty-core@4.0.0--canary.313.f7733aa.0
yarn add @ukho/admiralty-react@4.0.0--canary.313.f7733aa.0
```
</details>
> Fix theme typo for font-size-7

- packages/website/src/app/components/layout.tsx
- packages/website/src/app/components/link/link.mdx
- packages/website/src/app/components/link/page.tsx
- packages/website/src/usage/link/basic/angular.mdx
- packages/website/src/usage/link/basic/demo.tsx
- packages/website/src/usage/link/basic/index.mdx
- packages/website/src/usage/link/basic/javascript.mdx
- packages/website/src/usage/link/basic/react.mdx
- packages/website/src/usage/link/open-in-new-tab/angular.mdx
- packages/website/src/usage/link/open-in-new-tab/demo.tsx
- packages/website/src/usage/link/open-in-new-tab/index.mdx
- packages/website/src/usage/link/open-in-new-tab/javascript.mdx
- packages/website/src/usage/link/open-in-new-tab/react.mdx
#332 
Add link component example to documentation website.
Includes **basic link** and **open link in new tab** variants.
> 332 Add link component to Documentation Website

- packages/core/src/components.d.ts
- packages/core/src/components/autocomplete/autocomplete.interface.ts
- packages/core/src/components/autocomplete/autocomplete.tsx
<details>
<summary>📦 Published PR as canary version: <code>4.2.1--canary.366.e22dc68.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@4.2.1--canary.366.e22dc68.0
npm install @ukho/admiralty-core@4.2.1--canary.366.e22dc68.0
npm install @ukho/admiralty-react@4.2.1--canary.366.e22dc68.0
yarn add @ukho/admiralty-angular@4.2.1--canary.366.e22dc68.0
yarn add @ukho/admiralty-core@4.2.1--canary.366.e22dc68.0
yarn add @ukho/admiralty-react@4.2.1--canary.366.e22dc68.0
```
</details>
> Fixing the broken option export causing Angular builds to fail when using autocomplete component

- packages/docs/components/text-side-bar-item/customProps.mdx
- packages/docs/components/text-side-bar-item/props.mdx
- packages/website/src/app/brand-guide/styles.module.css
- packages/website/src/app/components/styles.module.css
- packages/website/src/app/components/text-side-bar/text-side-bar.mdx
- packages/website/src/app/get-help/styles.module.css
- packages/website/src/app/getting-started/styles.module.css
- packages/website/src/app/layout.tsx
- packages/website/src/app/patterns/styles.module.css
- packages/website/src/app/principles/page.tsx
- packages/website/src/app/principles/principles.mdx
- packages/website/src/app/principles/styles.module.css
- packages/website/src/app/updates/styles.module.css
- packages/website/src/app/updates/v5/v5.mdx
- packages/website/src/components/colour-blocks/colour-blocks.tsx
- packages/website/src/components/image-banner/image-banner.css
- packages/website/src/components/image-banner/image-banner.tsx
This fixes the following:
- Missing padding at the bottom of each page.
- Renamed side bar to text side bar on the text side bar component page.
- Fixed broken links on the homepage
- Fixed the v5 update, hero slightly cut off on laptop screen and there is a horizontal scrollbar
- Updated updates page heading to be a paragraph
- Updated privacy policy to navigate to admiralty privacy policy in a new tab
<details>
<summary>📦 Published PR as canary version: <code>5.0.1--canary.391.d743535.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@5.0.1--canary.391.d743535.0
npm install @ukho/admiralty-core@5.0.1--canary.391.d743535.0
npm install @ukho/admiralty-react@5.0.1--canary.391.d743535.0
yarn add …
```
> Fixed issues after v5 release

- packages/website/src/app/layout.tsx
Fixed this by adding the HREF to the anchor to make it focusable 
<details>
<summary>📦 Published PR as canary version: <code>5.0.2--canary.395.cc2f4c7.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@5.0.2--canary.395.cc2f4c7.0
npm install @ukho/admiralty-core@5.0.2--canary.395.cc2f4c7.0
npm install @ukho/admiralty-react@5.0.2--canary.395.cc2f4c7.0
yarn add @ukho/admiralty-angular@5.0.2--canary.395.cc2f4c7.0
yarn add @ukho/admiralty-core@5.0.2--canary.395.cc2f4c7.0
yarn add @ukho/admiralty-react@5.0.2--canary.395.cc2f4c7.0
```
</details>
> Fix: side nav item not focusing when tabbing

- packages/website/src/app/getting-started/javascript/javascript.mdx
Updated the documentation to clarify the CDN URL's and modified documentation to be clearer on projects which cannot use package managers
<details>
<summary>📦 Published PR as canary version: <code>5.0.2--canary.396.4dfbdc6.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@5.0.2--canary.396.4dfbdc6.0
npm install @ukho/admiralty-core@5.0.2--canary.396.4dfbdc6.0
npm install @ukho/admiralty-react@5.0.2--canary.396.4dfbdc6.0
yarn add @ukho/admiralty-angular@5.0.2--canary.396.4dfbdc6.0
yarn add @ukho/admiralty-core@5.0.2--canary.396.4dfbdc6.0
yarn add @ukho/admiralty-react@5.0.2--canary.396.4dfbdc6.0
```
</details>
> Fix: website docs for JavaScript install

- .github/workflows/release-email.yml
- scripts/send-release-email.js
Automatically sends an email out when a new package version has been published and also dependant on repository environment variable being true
<details>
<summary>📦 Published PR as canary version: <code>5.0.2--canary.402.be67e5d.0</code></summary>
<br />
```bash
npm install @ukho/admiralty-angular@5.0.2--canary.402.be67e5d.0
npm install @ukho/admiralty-core@5.0.2--canary.402.be67e5d.0
npm install @ukho/admiralty-react@5.0.2--canary.402.be67e5d.0
yarn add @ukho/admiralty-angular@5.0.2--canary.402.be67e5d.0
yarn add @ukho/admiralty-core@5.0.2--canary.402.be67e5d.0
yarn add @ukho/admiralty-react@5.0.2--canary.402.be67e5d.0
```
</details>
> Feat: release email logic
